name = "dronewind-push"
main = "worker.js"
compatibility_date = "2024-01-01"

[triggers]
crons = ["0 6,7,9,12,15,18,20,21 * * *"]

[[kv_namespaces]]
binding = "SUBS"
id = "e8bd376d61fc47c98cf48b1a6b6c748b"

[vars]
VAPID_PUBLIC = "BCklCWQe0Ha68Ro6KAKMYMn6jcaTo4WF92s3sMwRBuAUgFW3zsGgoZjSNrfRqIbBHe4O9WMhfQDOTT-IDypL5gY"
VAPID_PRIVATE = "EukltN9uIgR_IKsI348AsgUjzAOc8pIoAef2BNucW5c"
VAPID_SUBJECT = "mailto:cuccu.mauro92@gmail.com"
